In [16]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics 
import json

In [10]:
# ?load the clean data
df = pd.read_csv('framingham_cleandata.csv')
# Dropping Unnamed:0 column
df = df.drop(['Unnamed: 0'], axis=1)
df.head(10)

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   
5     0   43        2.0              0         0.0     0.0                0   
6     0   63        1.0              0         0.0     0.0                0   
7     0   45        2.0              1        20.0     0.0                0   
8     1   52        1.0              0         0.0     0.0                0   
9     1   43        1.0              1        30.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   
5             1         0    228.0  180.0  110.0  30.30       77.0     99.0   
6             0         0    205.0  138.0   71.0  33.11       60.0     85.0   
7             0         0    313.0  100.0   71.0  21.68       79.0     78.0   
8             1         0    260.0  141.5   89.0  26.36       76.0     79.0   
9             1         0    225.0  162.0  107.0  23.61       93.0     88.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0  
5           0  
6           1  
7           0  
8           0  
9           0

In [28]:
df_test = df.drop(['education', 'TenYearCHD'], axis = 1)
result = df_test.iloc[0].to_dict()
result

{'male': 1.0,
 'age': 39.0,
 'currentSmoker': 0.0,
 'cigsPerDay': 0.0,
 'BPMeds': 0.0,
 'prevalentStroke': 0.0,
 'prevalentHyp': 0.0,
 'diabetes': 0.0,
 'totChol': 195.0,
 'sysBP': 106.0,
 'diaBP': 70.0,
 'BMI': 26.97,
 'heartRate': 80.0,
 'glucose': 77.0}

In [11]:
df.columns

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [8]:
# Dropping Education column
df = df.drop(['education'], axis=1)

In [4]:
# logistic regression Model
X=df.drop('TenYearCHD', axis=1)
y=df['TenYearCHD'] != 1

In [5]:
# Split the data into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
# Scale the data and fit the model
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
# Train the Logistic Regression model on the unscaled data and print the model score
# create logistic model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [7]:
# predict class labels for the test set
predicted = model.predict(X_test_scaled)
predicted

array([ True,  True,  True, ...,  True,  True,  True])

In [8]:
# generate class probabilities
# probs = model.predict_proba(X_test)
# probs

In [9]:
# generate evaluation metrics
print(metrics.accuracy_score(y_test, predicted))


0.8603773584905661


In [10]:
# # Make the predictions
print(f"Training Data Score: {model.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model.score(X_test_scaled, y_test)}")

Training Data Score: 0.8547169811320755
Testing Data Score: 0.8603773584905661


In [ ]:
# X_train.head(2)

In [15]:
model.predict(np.array([[1,55,1,10.0,1,1,1,1,150.0,179.0,120.0,35.0,152.0,199.0]]))



array([False])

In [16]:
userinput = np.array([[0,20,0,0.0,0.0,0,1,0,110.0,110.0,70.0,22.0,70.0,100.0]])

In [13]:
model.predict(userinput)


array([False])

In [14]:
import pickle
pickle.dump(model, open('model.pickle', 'wb'))